[build]
  command = "node build.js"
  publish = "."

# Folders without trailing slash to index.html
[[redirects]]
  from = "/games/:game"
  to = "/games/:game/index.html"
  status = 200

# Folders with trailing slash to index.html
[[redirects]]
  from = "/games/:game/"
  to = "/games/:game/index.html"
  status = 200
